# Generated by Django 5.2.13 on 2026-04-23 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient_id'], name='audit_acces_patient_521ba4_idx'), models.Index(fields=['timestamp'], name='audit_acces_timesta_175bbb_idx')],
            },
        ),
    ]
