# Generated by Django 5.2.13 on 2026-04-23 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(unique=True)),
                ('patient_type', models.CharField(choices=[('user', 'User'), ('family', 'Family Profile')], max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('chronic_conditions', models.JSONField(blank=True, default=list)),
                ('current_medications', models.JSONField(blank=True, default=list)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('is_emergency_mode_enabled', models.BooleanField(default=False)),
                ('emergency_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Data',
                'verbose_name_plural': 'Emergency Data',
            },
        ),
    ]
