# Generated by Django 5.2.12 on 2026-04-25 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lab_name", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "lab"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Profile",
                "verbose_name_plural": "Lab Profiles",
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_id", models.UUIDField()),
                (
                    "patient_type",
                    models.CharField(
                        choices=[("user", "User"), ("family", "Family Profile")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                ("test_description", models.TextField(blank=True)),
                ("result", models.TextField(blank=True, null=True)),
                (
                    "result_file_key",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("doctor_remarks", models.TextField(blank=True, null=True)),
                ("prescribed_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_tests",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "lab_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_tests",
                        to="labs.labprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Test",
                "verbose_name_plural": "Lab Tests",
                "ordering": ["-prescribed_at"],
            },
        ),
    ]
