# Generated by Django 5.2.13 on 2026-04-23 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relation', models.CharField(choices=[('child', 'Child'), ('parent', 'Parent'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=50)),
                ('unique_health_id', models.CharField(max_length=20, unique=True)),
                ('qr_code_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Profile',
                'verbose_name_plural': 'Family Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
